"""add deadline

Revision ID: 044a8288dfb9
Revises: c37aca56ee08
Create Date: 2023-10-23 13:43:07.230706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '044a8288dfb9'
down_revision = 'c37aca56ee08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('deadline')

    # ### end Alembic commands ###
