"""add cascade

Revision ID: 5a3de6bd43b6
Revises: 1c6a7369c1f4
Create Date: 2023-10-23 20:18:52.741147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3de6bd43b6'
down_revision = '1c6a7369c1f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_projects', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tasks_projects'), 'projects', ['project_id'], ['project_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_projects'), type_='foreignkey')
        batch_op.create_foreign_key('fk_tasks_projects', 'projects', ['project_id'], ['project_id'])

    # ### end Alembic commands ###
